import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/Navbar'
import Footer from "./components/Footer"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Best Trail Website',
  description: 'Generated by Jiaxin',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className={inter.className}>
        <NavBar />
        <div className="border-t pt-20">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
